---
name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

  pull_request:
    branches:
      - main

  schedule:
    - cron: "15 6 * * 0"
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs:
  j1-ubuntu-setup:
    name: ubuntu
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: ğŸ” Github Event Name
        run: echo "event name is:" ${{ github.event_name }} 
      - name: ğŸŒ² Branch Name
        run: echo "Current working branch is:" ${{ github.ref}} 
      - name: ğŸ“‚ List Files
        run: echo "Files in repo:" ls ${{ github.workspace}}

  j2-test:
    name: test-ubuntu-after-build
    runs-on: ubuntu-22.04
    environment: Test
    steps:
      - name: Run tests
        run: echo "Testing..."
  
  j3-load-test:
    name: load-test-ubuntu
    runs-on: ubuntu-latest
    environment: Load-Test
    steps:
      - name: Run tests
        run: echo "Testing..."
      
      - name: Sleep for 15 seconds
        run: | 
          sleep 15
          echo "Whoops I fell asleep for a few seconds!" 